[package]
name = "augecoin-network"
version = "0.1.0"
edition = "2021"

[dependencies]
augecoin-core = { path = "../augecoin-core" }
augecoin-crypto = { path = "../augecoin-crypto" }
augecoin-storage = { path = "../augecoin-storage" }
ed25519-dalek = { version = "2", features = ["rand_core"] }
futures = "0.3"
libp2p = { version = "0.56", features = ["tcp", "tokio", "noise", "yamux", "ping", "identify", "macros", "gossipsub", "kad"] }
libp2p-connection-limits = "0.6"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
crossbeam-channel = "0.5"
tracing = "0.1"
