#!/usr/bin/env bash
# build-wasm.sh — regenerate the AUGECOIN WASM crypto package from Rust.
#
# Flow (matches FASE 3 of the hardening work):
#   Rust -> cargo build --target wasm32-unknown-unknown -> wasm-bindgen -> pkg/ -> SDK
#
# Output is written into packages/wasm-crypto/, which the TypeScript SDK
# consumes via `@augecoin/wasm-crypto` (file:../wasm-crypto). The glue
# (augecoin_crypto_bg.js) is generated by wasm-bindgen — never written by hand.
set -euo pipefail

cd "$(dirname "$0")/.."

CRATE="augecoin-crypto"
LIB_NAME="augecoin_crypto"
OUT_DIR="packages/wasm-crypto"
TARGET="wasm32-unknown-unknown"
PROFILE="release"

echo "[wasm] building ${CRATE} for ${TARGET} (${PROFILE})"
cargo build --target "${TARGET}" --release -p "${CRATE}"

WASM_BIN="target/${TARGET}/${PROFILE}/${LIB_NAME}.wasm"

if ! command -v wasm-bindgen >/dev/null 2>&1; then
    echo "[wasm] ERROR: wasm-bindgen CLI not found." >&2
    echo "[wasm] Install it with: cargo install wasm-bindgen-cli --version 0.2.127" >&2
    exit 1
fi

echo "[wasm] running wasm-bindgen -> ${OUT_DIR}"
mkdir -p "${OUT_DIR}"
wasm-bindgen --target bundler --out-dir "${OUT_DIR}" "${WASM_BIN}"

echo "[wasm] generated:"
ls -1 "${OUT_DIR}"

echo "[wasm] done. Run 'npm test' in packages/sdk-ts to verify parity."
